# Generated by Django 5.2.9 on 2026-06-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('admin', 'Администрирование'), ('accounting', 'Учёт и ошибки'), ('development', 'Разработка'), ('integration', 'Интеграции')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование работы')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от, ₽')),
                ('price_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до, ₽')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Если цена не указана — рассчитается по ставке за час.', max_digits=5, null=True, verbose_name='Оценка, часов')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField(default=1500, help_text='Используется для расчёта примерной стоимости типовых задач.', verbose_name='Стоимость часа работы, ₽')),
                ('telegram_contact_url', models.URLField(blank=True, help_text='Например: https://t.me/your_username', verbose_name='Ссылка на Telegram')),
                ('max_contact_url', models.URLField(blank=True, help_text='Ссылка для связи в мессенджере MAX.', verbose_name='Ссылка на MAX')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Получите у @BotFather. Нужен для дублирования заявок.', max_length=120, verbose_name='Токен Telegram-бота')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата или группы, куда отправлять заявки (например: -1001234567890).', max_length=64, verbose_name='Chat ID для уведомлений')),
                ('telegram_notify_enabled', models.BooleanField(default=False, verbose_name='Дублировать заявки в Telegram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('specialization', models.CharField(max_length=250, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='Кратко о специалисте')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Команда',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TypicalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Оценка, часов')),
                ('duration', models.CharField(max_length=80, verbose_name='Срок выполнения')),
                ('is_featured', models.BooleanField(default=False, help_text='Только одна задача рекомендуется для Hero.', verbose_name='Показывать в блоке Hero')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Типовая задача',
                'verbose_name_plural': 'Типовые задачи',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='telegram_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено в Telegram'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='landing.teammember', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
