# Generated by Django 5.2.9 on 2026-06-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Например: rel_1c_ut11', max_length=40, unique=True, verbose_name='Код конфигурации')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать в калькуляторе')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Конфигурация 1С',
                'verbose_name_plural': 'Конфигурации 1С',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OneCRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='Номер релиза')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('from_versions', models.JSONField(default=list, help_text='Список версий, с которых можно обновиться на этот релиз.', verbose_name='Обновление с версий')),
                ('min_platform', models.CharField(blank=True, help_text='Например: 8.3.27.1859', max_length=32, verbose_name='Мин. версия платформы')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='0 — самый новый релиз в конфигурации.', verbose_name='Порядок (меньше = новее)')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='landing.onecconfiguration', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Релиз 1С',
                'verbose_name_plural': 'Релизы 1С',
                'ordering': ['sort_order', '-release_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'version'), name='unique_release_per_configuration')],
            },
        ),
    ]
