# Generated by Django 5.2.9 on 2026-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_seed_onec_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='update_hours_per_release',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Трудозатраты на установку одного промежуточного обновления в калькуляторе.', max_digits=4, verbose_name='Часов на один релиз обновления'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=1500, help_text='Используется для расчёта примерной стоимости типовых задач и обновлений.', verbose_name='Стоимость часа работы, ₽'),
        ),
    ]
