# Generated by Django 5.2.9 on 2026-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_sitesettings_update_hours_per_release_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('error', 'Ошибка')], default='running', max_length=16, verbose_name='Статус')),
                ('triggered_by', models.CharField(choices=[('manual', 'Вручную'), ('scheduler', 'Планировщик'), ('force', 'Принудительно')], default='manual', max_length=16, verbose_name='Источник')),
                ('configurations_total', models.PositiveSmallIntegerField(default=0, verbose_name='Конфигураций всего')),
                ('configurations_synced', models.PositiveSmallIntegerField(default=0, verbose_name='Конфигураций успешно')),
                ('configurations_failed', models.PositiveSmallIntegerField(default=0, verbose_name='Конфигураций с ошибкой')),
                ('configs_created', models.PositiveSmallIntegerField(default=0, verbose_name='Новых конфигураций')),
                ('configs_updated', models.PositiveSmallIntegerField(default=0, verbose_name='Обновлённых конфигураций')),
                ('releases_created', models.PositiveIntegerField(default=0, verbose_name='Релизов создано')),
                ('releases_updated', models.PositiveIntegerField(default=0, verbose_name='Релизов обновлено')),
                ('releases_deleted', models.PositiveIntegerField(default=0, verbose_name='Релизов удалено')),
                ('message', models.TextField(blank=True, verbose_name='Сводка')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Лог синхронизации релизов',
                'verbose_name_plural': 'Логи синхронизации релизов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='freesc_auto_sync_enabled',
            field=models.BooleanField(default=True, help_text='Периодически загружать релизы с freesc.ru в калькулятор.', verbose_name='Автосинхронизация релизов с freesc.ru'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='freesc_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация релизов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='freesc_sync_interval_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Интервал синхронизации, дней'),
        ),
    ]
