# Generated by Django 5.2.9 on 2026-06-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_pricelistitem_hours_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Иконка вкладки браузера. Рекомендуется PNG или ICO, 32×32 или 64×64 px.', upload_to='site/', verbose_name='Favicon'),
        ),
    ]
