# Generated by Django 5.2.15 on 2026-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Отображается в блоке контактов и в юридических документах.', max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Например: +7 (999) 123-45-67', max_length=30, verbose_name='Телефон для связи'),
        ),
    ]
