# Generated by Django 5.2.9 on 2026-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_sitesettings_contact_email_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='is_honeypot',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Honeypot'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_honeypot_leads',
            field=models.BooleanField(default=False, help_text='По умолчанию заявки, попавшие в антиспам, скрыты в списке заявок.', verbose_name='Показывать заявки из honeypot в админке'),
        ),
    ]
