# Generated by Django 5.2.9 on 2026-06-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_leadrequest_honeypot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Код маршрута')),
                ('name', models.CharField(max_length=200, verbose_name='Название миграции')),
                ('source_name', models.CharField(max_length=200, verbose_name='Исходная конфигурация')),
                ('target_name', models.CharField(max_length=200, verbose_name='Целевая конфигурация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_hours', models.DecimalField(decimal_places=1, default=0, help_text='Используется, если этапы не заданы.', max_digits=6, verbose_name='Базовая оценка, часов')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Маршрут миграции',
                'verbose_name_plural': 'Маршруты миграции',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MigrationPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Этап')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Оценка, часов')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('migration_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='landing.migrationpath', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Этап миграции',
                'verbose_name_plural': 'Этапы миграции',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
