# Generated by Django 5.2.9 on 2026-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(blank=True, help_text='Отображается в списке статей и в meta description, если не задано отдельно.', verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Обложка')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
