# Generated by Django 5.2.9 on 2026-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(help_text='Поддерживается Markdown: **жирный**, *курсив*, `код`, блоки кода, списки, заголовки, ссылки и таблицы.', verbose_name='Текст статьи'),
        ),
    ]
